# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Test with specific devices"
  lane :tests do
    run_tests(workspace: "Animal\ Crossing.xcworkspace",
            devices: ["iPhone 12 Pro Max"],
            scheme: "Animal\ Crossing",
            build_for_testing: true)

    run_tests(scheme: “AC_unitTest”,
             workspace: “Animal\ Crossing.xcworkspace”,
             devices: ["iPhone 12 Pro Max"],
             xctestrun: "/Users/leahjoyylaya/Library/Developer/Xcode/DerivedData/Animal_Crossing-fvhgzvozkqelzghkmxdzvvubnxfj/Build/Products/Animal Crossing_iphonesimulator14.2-x86_64.xctestrun")
  end
end
